server:
  port: 8080
spring:
  application:
    name: reggie_take_out
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/restaurant?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: root
#      password: '020920'
  #Redis配置
  redis:
    host: localhost
    port: 6379
    #password:
    database: 0
  #Spring Cache配置
  cache:
    redis:
      time-to-live: 1800000 #缓存数据的过期时间 单位毫秒

  #配置Sharding JDBC
  shardingsphere:
    datasource:
      #配置主从数据源名称 上下要对应 这里设置的是什么 下面就是什么
      names:
        master,slave
      #主数据源 - 名称为上面设置的master - 对应设置的Windows本机
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/restaurant?characterEncoding=utf-8&userSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: '020920'
      #从数据源 - Linux虚拟机
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.88.92:3306/restaurant?characterEncoding=utf-8&userSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: Wyh0920^
    masterslave:
      # 读写分离配置 - 负载均衡
      load-balance-algorithm-type: round_robin #轮询
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示，默认false
  main:
    #定义允许bean定义覆盖配置
    allow-bean-definition-overriding: true

#MP配置
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

#自定义变量
wyh:
  path: D:\TempFile\takeoutImage\ #外卖菜品套餐图片文件保存路径